#!/bin/bash
#SBATCH --job-name=transfer_PEARO
#SBATCH --partition=transfert
#SBATCH --time=02:00:00
#SBATCH --output=logs/transfer_PEARO_%j.out
#SBATCH --error=logs/transfer_PEARO_%j.err

set -euoxv pipefail

DAY_FMT="$1"
DATA_INDIR="$2"

SCRIPT_DIR="$SLURM_SUBMIT_DIR"
echo "$0: SCRIPT_DIR: $SCRIPT_DIR"
CONFIG_DIR=$SCRIPT_DIR/config_input

echo "Transfer data for $DAY_FMT"

"$SCRIPT_DIR/fetch_one_day.sh" "$CONFIG_DIR/lof_${DAY_FMT}.txt" "$DATA_INDIR"

echo "Transfer done for $DAY_FMT"

# jid_prepro=$(sbatch --parsable preprocess_one_day.job "$DAY_FMT")
# ###sbatch --dependency=afterok:$SLURM_JOB_ID preprocess_one_day.job "$DAY_FMT"

# echo "Submitted preprocessing job $jid_prepro for $DAY_FMT"
